### PR TITLE
update z-push to new repo-backed version.

### LINKED ISSUE #584: update z-push to 2.3.1 from new package repos
the new version of z-push is available via repos and requires slightly different configuration. PR en route.

### PR DESCRIPTION
**Pull request by oskapt**
This PR will remove any existing source installation of z-push and install it from their new Ubuntu/Debian repos. It also splits out the configuration into the new backend-specific configuration and installs all the requisite packages.

I have this running in production under Ubuntu 14.04.

This closes #584.

### CODE REVIEW

**Comment by ariddell** [comment]
Thanks @oskapt . Do there need to be any changes on the jessie branch?

**Comment by oskapt** [comment]
@ariddell It isn't tested on Jessie, but it's configured to work on all three. I'm running it on Ubuntu. Someone should run it just to make sure I didn't miss anything - afaict the only difference is the repository path.

**Comment by mikeashley** [comment]
@oskapt I think this PR is headed in a good direction.  Do you have any interest in reworking it for the jessie branch?  I don't know if anybody will champion it for wheezy.  If you are not interested I will probably pick it up.

**Comment by oskapt** [comment]
I'm going off on my own.

**Pull request closed without merging**
