### PR TITLE
sl: properly install changed certificate and restart apache on changes

### PR DESCRIPTION
**Pull request by danmilon**
I was stupidly using the certificates provided in the repo, and then I generated some self-signed ones but found out that they were not properly installed. The `creates=/etc/ssl/certs/wildcard_combined.pem` was making the task to skip which it shouldn't. So I fixed that, and also thought it should restart apache by itself.

### CODE REVIEW

**Comment by neuhaus** [comment]
Can you please make a separate PR for the SSL stapling thing?

**Comment by danmilon** [comment]
See #434

**Comment by danmilon** [comment]
I also removed the SSL stapling from this PR.

**Comment by neuhaus** [comment]
fixes #190, #412 and #449

**Pull request merged**
