### PR TITLE
Switching to Ansible 2

### PR DESCRIPTION
**Pull request by synchrone**
So it's been a year since https://github.com/sovereign/sovereign/issues/538.
Sovereign runs well, except for one `shell:` invocation acting up with ansible 2.

### CODE REVIEW

**Comment by ariddell** [comment]
Thanks for this. I'd be in favor of merging this. What little I do with Ansible is with 2.0

**Comment by synchrone** [comment]
okay, so who else needs to review this?
I'd like to have this merged, since it would enable a prospective route53/google cloud dns role, as those modules are only available in Ansbile 2.2+

**Comment by ariddell** [comment]
Anyone else have thoughts? This is a big change.

**Comment by ariddell** [comment]
OK. In the spirit of http://rfc.zeromq.org/spec:42/C4 I'm going to merge this. If anyone's upset, submit a PR reverting it.

**Pull request merged**
