### PR TITLE
Change shell to copy content

### PR DESCRIPTION
**Pull request by spk**
Hi, Just removing `shell` to `copy` with `content` option that IMHO is cleaner.
Cheers

### CODE REVIEW

**Comment by spk** [comment]
But no idempotent

**Comment by nodiscc** [comment]
@spk May I ask in what case this would break? Trying to learn more about ansible and your patch looks fine to me.

**Comment by spk** [comment]
Hi @nodiscc, it does not break anything but even if this not changed the `dest` ansible will see as changed every time we play the playbook, it should be idempotent if not change has been made.
Maybe there is a solution on the Internet

**Comment by spk** [comment]
Yes https://github.com/mtpereira/ansible-common/blob/8e693b3db3b15c440428f378e13ce8d04186d637/tasks/timezone-debian.yml

**Comment by spk** [comment]
@nodiscc I've submitted another PR, thanks for the question it help me to fix the problem!

**Pull request closed without merging**
