### PR TITLE
add www.domain DNS entry to README.md

### PR DESCRIPTION
**Pull request by Dosenpfand**

### CODE REVIEW

**Comment by mikeashley** [comment]
What error do you see if this is omitted?  You shouldn't need it if you don't include the blog role.

**Comment by Dosenpfand** [comment]
I get a DNS  error by letsencrypt, because the entry does not exist:
> Domain: www.mydomain.com
> Type:   connection
> Detail: DNS problem: NXDOMAIN looking up A for www.mydomain.com

Upon closer inspection I think it should not fail otherwise since [letsencrypt-gencert](https://github.com/sovereign/sovereign/blob/jessie/roles/common/files/letsencrypt-gencert) checks the hosts existense first. I don't know why it failed in my case.
Nevertheless I think the README should include the www entry, maybe with it's role.

**Comment by ariddell** [comment]
#524 is related. What if we just skipped the naked domain entirely and shifted the blog to www.domain?

**Comment by mikeashley** [comment]
I'm not sure it's related.  Root cause on this one still hasn't been identified.

**Comment by mikeashley** [comment]
@Dosenpfand This is a good update to the README.  Please squash the commit, and I'll merge it in.

**Comment by Dosenpfand** [comment]
@mikeashley done

**Pull request merged**
