### PR TITLE
Use wget to add apt-key for OwnCloud rather that apt_key module.

### PR DESCRIPTION
**Pull request by alexec**

### CODE REVIEW

**Comment by alexec** [comment]
The URL parameter fails SSL verification checks, `wget` does not. This is a problem on both Ubuntu and Debian.

**Comment by jplock** [comment]
I haven't experienced the SSL verification issue on Trusty.

**Comment by mikeashley** [comment]
Likewise, I have not had any problem with SSL verification checks.  Is this something you can reproduce in a test environment?

**Comment by mikeashley** [comment]
Closing this since it does not appear to be a needed change.  Please resubmit if this is reproducible in a test environment.

**Pull request closed without merging**
