### PR TITLE
vpn: add systemd compatibility for rc.local

### PR DESCRIPTION
**Pull request by Friz-zy**
I don't have system for check it right now but it should help.

### CODE REVIEW

**Comment by ariddell** [comment]
Thanks so much for your work on this.

Let's merge the systemd stuff into the jessie branch and split the mtu fix out.

Is there any ansible pattern for "if X is defined, then Y"? It would be nice to avoid putting the 'tun-mtu' in the variable name itself.

**Comment by Friz-zy** [comment]
Sorry, I want split two pull requests but github automatically pushed second commit to opened PR =\

Yes, Ansible has this pattern:
```
- debug: msg="Defined!"
  when: variable is defined
```

**Comment by ariddell** [comment]
So can we do something like ``{% if variable is defined %}tun-mtu {{ variable }} {% endif %}``?

Can we be more explicit about the instructions for iOS users? Can they set the variable to ``None`` or something instead of commenting the line out?

If you don't want to deal with github's PR system I'm happy to split out your commits (when they're done) and cherry-pick them into separate pull requests.

**Comment by Friz-zy** [comment]
You gave me good advice with cherry-pick ;)
I'll split it to two different PR.

Yep, It's a good point: because it's a jinja template we can check if variable exists and not false\empty. Nice solution!

**Comment by ariddell** [comment]
This still needs some work. @Friz-zy you mentioned you would split this into different PRs. Looking forward to them.

**Pull request closed without merging**
