### PR TITLE
Correct mailserver configuration

### PR DESCRIPTION
**Pull request by mikeashley**
Some configuration files were not getting installed.  Also, rmilter is no longer needed with the rspamd 1.6.

### CODE REVIEW

**Comment by mikeashley** [comment]
This pull request reinstates solr for fast searching, but it looks like it is broken.  GET requests are returning 500s (internal server error).  I'm investigating.  Recommend holding off merging until I get to the bottom of it.

**Comment by mikeashley** [comment]
The solr error was a goose chase.  Solr is working fine with dovecot, verified with Solr's web interface and both dovecot's and tomcat's logs when searching using Roundcube.

**Comment by mikeashley** [comment]
I updated this PR after merging #708 .  It's baked for two weeks now on my production server with no problems, and Iv'e been reviewing rspamd's logs using its admin web UI.  I think this is ready to merge.

**Comment by mikeashley** [comment]
This PR addresses issues #637, #661, and #691.

**Comment by neuhaus** [comment]
Looks good. One thing i noticed is that the DoveCot AntiSpam plugin has been deprecated.
See https://wiki2.dovecot.org/Plugins/Antispam
Is this something we should be doing instead?

**Comment by mikeashley** [comment]
I noticed that too.  We've got a couple of issues with sieve (#647, #608).  I was thinking of tackling that separately once I get through this PR and the two behind it to address DMARC and DKIM setup.

**Pull request merged**
