### PR TITLE
Pin Selfoss version to an actual release

### PR DESCRIPTION
**Pull request by jplock**
Cherry pick this commit from the `jessie` branch

### CODE REVIEW

**Comment by neuhaus** [comment]
thanks

**Comment by simontretter** [comment]
This breaks it for me on new installs (ubuntu 14.04, ansible 2.0.0.2).

`fatal: [8.8.8.8]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File
\"/home/google/.ansible/tmp/ansible-tmp-1454985227.82-826161849662/git\", line 2938, in <module>\r\n    main()\r\n  File \"/home/google/.ansible/tmp/ansible-tmp-1454985227.82-826161849662/git\", line 756, in
main\r\n    remote_head = get_remote_head(git_path, module, dest, version, remote, bare)\r\n  File \"/home/google/.ansible/tmp/ansible-tmp-1454985227.82-826161849662/git\", line 383, in get_remote_head\r\n
elif is_remote_branch(git_path, module, dest, remote, version):\r\n  File \"/home/google/.ansible/tmp/ansible-tmp-1454985227.82-826161849662/git\", line 439, in is_remote_branch\r\n    if version in
out:\r\nTypeError: 'in <string>' requires string as left operand, not float\r\n", "msg": "MODULE FAILURE", "parsed": false}`

**Comment by neuhaus** [comment]
Thanks. Can you please make a PR for this fix?

**Comment by neuhaus** [comment]
Never mind. I commited the fix.

**Comment by simontretter** [comment]
Thanks. You have the power ;-)

**Pull request merged**
