### PR TITLE
Avoid opportunity for copy-paste trouble

### PR DESCRIPTION
**Pull request by JasonGhent**
Also more scriptable, in vein of alternative commands provided

### CODE REVIEW

**Comment by ariddell** [comment]
Maybe add a note about what the ``sed`` command does for those who might not be familiar with it?

**Comment by JasonGhent** [comment]
Sure. sed is used here to truncate the hash type from the beginning of the doveadm output.

**Comment by ariddell** [comment]
Right, perhaps add such a note to the README.md? It's a good change. Thanks for this.

**Comment by JasonGhent** [comment]
Updated. 😄

**Comment by JasonGhent** [comment]
Any additional feedback?

**Comment by ariddell** [comment]
Looks great! Thanks.

**Pull request merged**
