### PR TITLE
Fix condition for rspamd Ubuntu repo installation.

### PR DESCRIPTION
**Pull request by carljm**

### CODE REVIEW

**Comment by carljm** [comment]
I'm also curious -- why the `download.suse.com` repos for rspamd, instead of the `rspamd.com` repos recommended at https://rspamd.com/downloads.html ? And why using repos labeled for Ubuntu 14.10 for 14.04?

**Comment by neuhaus** [comment]
Good questions. Looks like these are issues that should be fixed.

**Comment by carljm** [comment]
Shall I add the fixes for those two issues to this PR as well, or file separate PRs?

**Comment by neuhaus** [comment]
Yes please

**Comment by carljm** [comment]
Replaced by #486.

**Pull request closed without merging**
