### PR TITLE
change auth to internal_hashed

### PR DESCRIPTION
**Pull request by Rehwanne**
because why the fuck not?

### CODE REVIEW

**Comment by Rehwanne** [comment]
i mean: 
internal_hashed
```
jabber# cat testuser.dat 
return {
	["iteration_count"] = 4096;
	["stored_key"] = "b41671ca2918af11670a4422d45ed479e6091733";
	["salt"] = "69485fb6-8a23-4d9a-9f9f-52cfee7c8ca9";
	["server_key"] = "9e34072a6881dd8865859584f3cb6ac5e2f078f3";
};
```

internal_plain
```
jabber# cat testtest.dat 
return {
	["password"] = "test123";
};
```

**Comment by ariddell** [comment]
This looks great. What clients don't support this SCRAM protocol thing? https://prosody.im/doc/plain_or_hashed

**Comment by Rehwanne** [comment]
Gajim and Pidgin both support it, and I dont know of a client that doesnt.

**Comment by Rehwanne** [comment]
IMHO Clients that dont support SCRAM should not be used anyway.

**Comment by ariddell** [comment]
I don't use prosody so I can't test this. Perhaps someone else is an XMPP user?

**Comment by nodiscc** [comment]
I've always been using `internal_hashed` and it works fine with all clients I tested.

**Comment by ariddell** [comment]
Great. Thanks for this.

**Pull request merged**
