### PR TITLE
enabled password plugin and sql function for updating passwords

### PR DESCRIPTION
**Pull request by oskapt**
This PR creates a SQL function in the `mailserver` database for updating passwords and configures the password plugin for operation. It won't be useful without #576, so feel free to scrap this if you don't accept the other.

### CODE REVIEW

**Comment by ariddell** [comment]
Hi @oskapt . Thanks for all these PRs. Have you looked at the jessie branch? It's quite a bit ahead of master and perhaps might benefit from these changes.

**Comment by oskapt** [comment]
jessie is a non-starter because it's missing roundcube. i'm building this out for production to replace Fastmail - a web email client is important.

i ended up just deploying my stuff on Ubuntu, since that's where the rest of our environment is. i just moved my personal wheezy instance of sovereign to a new Ubuntu instance with all of the changes in these PRs. works great.

**Comment by mikeashley** [comment]
There's PR #507 on the jessie branch for reinstating roundcube.  You might have a look.

**Comment by oskapt** [comment]
I wrote my own playbook for installing Roundcube from source, and it works fine. I think I'm over submitting PRs here, since they seem to get attention from everyone _except_ the maintainer.

**Comment by neuhaus** [comment]
Thanks for the PR. I was on vacation for the last 4 weeks however mike is also one of the comitters.

**Comment by mikeashley** [comment]
I am not working on the wheezy branch.  Does any committer want to champion this PR?  If not, I will close it.

**Comment by oskapt** [comment]
I'm going off on my own.

**Pull request closed without merging**
