### PR TITLE
update openvpn server config

### PR DESCRIPTION
**Pull request by Friz-zy**
Change default network buffer size
Should increase tcp tunnel speed for openvpn < 2.3.9
https://community.openvpn.net/openvpn/ticket/461

### CODE REVIEW

**Comment by ariddell** [comment]
Thanks for this! Would you mind adding a note about which version of openvpn has this included so we can know when it's no longer needed (perhaps the release after Jessie)?

**Comment by ariddell** [comment]
@Friz-zy on another note, do you have a working openvpn config for jessie? We're missing that.

**Comment by Friz-zy** [comment]
Even unstable sid right now [uses 2.3.7](https://packages.debian.org/search?keywords=openvpn) so it will be not so soon...
About config: what's the problem?
Unfortunately, I am using an older version of Ubuntu with not the most fresh openvpn.

**Comment by ariddell** [comment]
But there is a release which includes the fix, right? We should note that.

re: config, jessie uses systemd, so a few things need to change.

**Comment by Friz-zy** [comment]
Fix will be in openvpn 2.3.9, but I don't know what distro will include it.
With systemd you have a problem with rc.local, haven't it?
I can fix it by rc-local.service, if you want.

**Comment by ariddell** [comment]
Oh, I'm sorry -- I didn't realize you included the version number in the
first place.

**Comment by jplock** [comment]
I can no longer connect to my VPN from my iPhone or iPad after this change.  Desktop works fine though.  Any thoughts?

**Comment by Friz-zy** [comment]
Hm, can you change
```
push "sndbuf 393216"
push "rcvbuf 393216"
```
to
```
+push "sndbuf 0"
+push "rcvbuf 0"
```
or delete it and post results here?

**Comment by jplock** [comment]
So after some trial and error, this PR is actually fine.  The problem I'm running into is with the `openvpn_mtu` change in https://github.com/sovereign/sovereign/pull/429.  I had to comment that out to be able to connect.  I'm running Debian Wheezy.

```
root@mail:/etc/openvpn# dpkg -l | grep openvpn
ii  openvpn                               2.2.1-8+deb7u3                    amd64        virtual private network daemon
```

**Pull request merged**
