### PR TITLE
Roundcube 1.1.4

### PR DESCRIPTION
**Pull request by mikeashley**
Here is a proposal to move from 0.9.5 to 1.1.4 that stops using Debian packages that have been unreliable.

I aimed for idempotency and therefore leave the user with some post-deploy finalization work to do.  I don't really like this, but I think idempotency is more important, and this also sets up for easier upgrades in the future.  Is this tradeoff ok?

### CODE REVIEW

**Comment by mikeashley** [comment]
Tests are passing for both wheezy and trusty.  The meaningful difference between the two is Apache 2.2 versus Apache 2.4.

**Comment by neuhaus** [comment]
I'd rather wait for Xenial to upgrade Roundcube to 1.1.4 using their standard package. For jessie we can use the jessie-backports repository to get Roundcube 1.1.4.
Meanwhile, issue #417 needs to be fixed by someone with some spare time to look into it.

**Comment by mikeashley** [comment]
I no longer trust the roundcube packages on debian.  The wheezy backport has been troublesome (see #417, and it's currently breaking in sovereign's test environment).  I suspect that the package is trying to do too much, roundcube simply isn't designed for packaging, or some combination of the two.  Upgrades through the package especially scare me at this point.

**Comment by neuhaus** [comment]
If it turns out that the version 1.1.4 packages give us problems we can use this pull request. For now, let's stick with the packages. Thanks.

**Pull request closed without merging**
